#! /bin/sh

#                    ___           ___         ___           ___
#     _____         /  /\         /  /\       /__/\         /__/\
#    /  /::\       /  /:/_       /  /::\     _\_ \:\       |  |::\
#   /  /:/\:\     /  /:/ /\     /  /:/\:\   /__/\ \:\      |  |:|:\  
#  /  /:/~/::\   /  /:/ /::\   /  /:/~/:/  _\_ \:\ \:\   __|__|:|\:\
# /__/:/ /:/\:| /__/:/ /:/\:\ /__/:/ /:/  /__/\ \:\ \:\ /__/::::| \:\ 
# \  \:\/:/~/:/ \  \:\/:/~/:/ \  \:\/:/   \  \:\ \:\/:/ \  \:\~~\__\/ 
#  \  \::/ /:/   \  \::/ /:/   \  \::/     \  \:\ \::/   \  \:\
#   \  \:\/:/     \__\/ /:/     \  \:\      \  \:\/:/     \  \:\
#    \  \::/        /__/:/       \  \:\      \  \::/       \  \:\
#     \__\/         \__\/         \__\/       \__\/         \__\/

###################
## configuration ##
###################

#autostart
$HOME/.config/bspwm/autostart.sh

## workspace name
## font needed wuncon-siji
bspc monitor eDP1 -d      

## common bspwm configuration
bspc config border_width       0
bspc config window_gap         	8
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config top_padding 24


## color settings
bspc config focused_border_color "#0c0F18" 
#bspc config focused_border_color "#0D0C0F"
bspc config normal_border_color "#0B0F18"
#bspc config normal_border_color "#0D0C0F"


##################
## window rules ##
##################

## monitor1
## workspace 1 
bspc rule -a firefox desktop=^1 follow=on focus=on
bspc rule -a Brave-browser desktop=^1 follow=on focus=on
bspc rule -a Nicotine desktop=^1 follow=on focus=on
## workspace 2
bspc rule -a JDownloader desktop=^2 follow=on focus=on
## workspace 3 
bspc rule -a smplayer desktop=^1 follow=on focus=on
bspc rule -a mpv desktop=^1 follow=on focus=on
bspc rule -a vlc desktop=^1 follow=on focus=on
## workspace 4 
bspc rule -a Subl3 desktop=^4 follow=on focus=on
## workspace 5 
bspc rule -a Steam desktop=^5 follow=on focus=on
bspc rule -a scummvm desktop=^5 follow=on focus=on
## workspace 6 
bspc rule -a Gimp-2.10 desktop=^6 follow=on focus=on
## workspace 7
## workspace 8 
## workspace 9 
## workspace 10 
## workspace agnostic
bspc rule -a Zathura state=tiled